### ISSUE TITLE
Mapping of MARS predicted IDs to groundtruth/reference dataset

### ISSUE THREAD

**Issue by estorrs** [snap-stanford/mars#13]
Should the MARS predicted cluster IDs map to the cluster IDs in the groundtruth/reference dataset?

I'm able to get cell type predictions with MARS, but they don't appear to be mapping back to the groundtruth cluster IDs.

This issue also seems to be present in the [example notebook](https://github.com/snap-stanford/mars/blob/master/notebooks/cellbench.ipynb) where the predicted cluster IDs don't line up with the reference cluster IDs (for example, in the visualization output for notebook cell 38 where ground_truth and MARS_labels don't appear to match up each other).

Thanks in advance!

**Comment by mbrbic** [comment]
No, they should not match because MARS does not use ground truth annotations. If you want to match them you can use Hungarian algorithm which solves assignment problem. To see how to do it, you can check [evaluation.py](https://github.com/snap-stanford/mars/blob/master/evaluation.py) where MARS clusters are mapped to ground truth clusters in order to compute accuracy, precision and recall.

**Comment by estorrs** [comment]
Thanks!
